### ISSUE TITLE
Set up of Auth0 

### ISSUE THREAD

**Issue by abigail-hampson** [torchbox/m-response#16]
- TBX to use test version initially 

- Nathan to update with specific tasks needed after further research

**Comment by NathHorrigan** [comment]
FE Tasks:
- [ ] Install Auth0 JS libraries
- [ ] Write Redux reducer/action-creators/selectors for auth logic and storing auth token
- [ ] Write container component for login screen that connects to redux state
- [ ] Wire together login screen, signup screen & welcome screen using React Router
- [ ] Setup React Router for protected routes (routes that need auth)

**Comment by tm-kn** [comment]
This has been deployed to staging.
