### ISSUE TITLE
Guide Book link doesn't work

### ISSUE THREAD

**Issue by madasan** [torchbox/m-response#189]
Expected behaviour: in Respond mode when replying to a review you can click the Guide Book link to open a document of canned responses. Document link is here (published to the web): https://docs.google.com/document/d/e/2PACX-1vQds-2DY62ztTCyaoyVr5myp5ZszUFhAyfGueTz5OF9Gi5UibS9LoMxAFkkMhlaH133WF6M3bggD8K4/pub

Actual behaviour: When clicking on the Guide Book nothing happens.

**Comment by johngian** [comment]
Verified in prod
