### ISSUE TITLE
Generate activity report on a weekly basis

### ISSUE THREAD

**Issue by madasan** [torchbox/m-response#201]
In order to check the status of this program we need to generate an activity report on a weekly basis. Format:

A spreadsheet (or any other format that makes sense) containing the following information:

- Number of active users (an active user = has submitted at least one reply or moderated at least one response in the last 7 days)

- Number of responses submitted 

- Number of responses that have passed moderation 

- Number of responses that are still in the queue for moderation (have received one or two moderations but not three)

-Number of responses that have been declined (went through all three moderations but did not pass)

- A listing of all responses that have been submitted including the corresponding reviews as well as their status (declined, approved, published etc.) For declined responses ideally we would also see the scoring they received for each of the three sections (tone, accuracy of solution, personalization).

This should be generated every Friday and sent to mana@mozilla.com and kpapadea@mozilla.com.

Let me know if the above needs to be broken into multiple bugs.

**Comment by johngian** [comment]
Fixed after #213  #211  #212
