### ISSUE TITLE
Domain Name

### ISSUE THREAD

**Issue by abigail-hampson** [torchbox/m-response#60]
-[ ] Mozilla to specify domain name 
- [x] Provide DNS details

**Comment by johngian** [comment]
The domain name we are going to use is: ```respond.mozilla.community``

**Comment by johngian** [comment]
As far as i remember we need to do some configuration in heroku level first and then add a CNAME in our domain to point to heroku.

@tm-kn Is that correct?

**Comment by tm-kn** [comment]
Yes, we'll need to point the CNAME record at:

`respond.mozilla.community.herokudns.com`

However we have not yet created the production app yet, therefore we should hold of until it's done (#59).

**Comment by johngian** [comment]
Cool, please ping me here to do the change.

**Comment by tm-kn** [comment]
#127 sets basic auth. After we've set it, we should be able to safely set the domain name.

**Comment by tm-kn** [comment]
Actually there's a basic auth on the production already. Just needed to configure it. We should be able to set it safely now.

**Comment by johngian** [comment]
I just added the DNS entry, its going to propagate soon:
```
;; QUESTION SECTION:
;respond.mozilla.community.	IN	CNAME

;; ANSWER SECTION:
respond.mozilla.community. 60	IN	CNAME	behavioral-waters-k5zn5urryfijkiijzsubzxmf.herokudns.com.
```
